### ISSUE TITLE
Can not run it

### ISSUE THREAD

**Issue by TranTruongMMCII** [argoniseur/TPs#1]
tdd1, tdd3, tdd4 can not run it, or it runs but it not give answer.

**Comment by argoniseur** [comment]
Hello, this repo is not maintained, mainly because it's old stuff for uni that I was just storing for private usage. Some work are even incomplete

**Comment by TranTruongMMCII** [comment]
Dear Sir/Madam,
Can I get the completed code to review it? I am sure that not use you code
for exam or assignment.

Thank you for your time and consideration.
